import { Inter } from "next/font/google";
import "./globals.css";
import HeaderMain from "./components/header";
import AuthContextProvider from "./context/AuthContext";
import Providers from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test for iApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <AuthContextProvider>
        <html lang="en">
          <body className={inter.className}>
            <HeaderMain />
            {children}
          </body>
        </html>
      </AuthContextProvider>
    </Providers>
  );
}
